version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - audio-network

  broker:
    build: ./audio-broker-service
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - audio-network

  worker:
    build: ./audio-worker-service
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - audio-network
    # Para Windows, pode ser necessário aumentar o timeout
    deploy:
      resources:
        limits:
          memory: 1G

  frontend:
    build: ./frontend-service
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - broker
    networks:
      - audio-network

networks:
  audio-network:
    driver: bridge

volumes:
  redis_data: